# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1
jobs:
  build-and-publish:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies- # fallback to using the latest cache if no exact match is found
      # - run:
      #     name: Prepare for testing
      #     command: |
      #       npm install --save-dev @testing-library/react
      # - run:
      #     name: Run unit-tests
      #     command: |
      #       npm run test a
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: yarn build
      - run:
          name: Compress Artifacts
          command: tar -cvzf tlvc-order-fe-build.tar build
      - store_artifacts:
          path: tlvc-order-fe-build.tar

workflows:
  version: 2.1
  sample-workflow:
    jobs:
      - build-and-publish
          # filters:  # using regex filters requires the entire branch to match
          #   branches:
          #     only:  # only branches matching the below regex filters will run
          #       - dev
