# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1
jobs:
  build-and-publish:
    docker:
      - image: circleci/node:latest
    working_directory: ~/tlvc-order-fe
    steps:
      - checkout
      - restore_cache:
          keys:
            - tlvc-dependencies-{{ checksum "package.json" }}
            - tlvc-dependencies- # fallback to using the latest cache if no exact match is found
      # - run:
      #     name: Prepare for testing
      #     command: |
      #       npm install --save-dev @testing-library/react
      # - run:
      #     name: Run unit-tests
      #     command: |
      #       npm run test a
      - run:
          name: Install dependencies
          command: | 
            cd ~/tlvc-order-fe
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: tlvc-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: yarn build
      - run:
          name: Compress Artifacts
          command: tar -cvzf tlvc-order-fe-build.tar build
      - store_artifacts:
          path: tlvc-order-fe-build.tar

workflows:
  version: 2.1
  sample-workflow:
    jobs:
      - build-and-publish
          # filters:  # using regex filters requires the entire branch to match
          #   branches:
          #     only:  # only branches matching the below regex filters will run
          #       - dev
